export const ROUTE_PATHS = {
  DEFAULT: "",
  LOGIN: "login",
  REGISTER: "register",
  PERMISSION_DENIED: "permission-denied",
  VOUCHER: "voucher",
  ORDER: "order",
  USER: "user",
  BLOG: "blog",
  BANNER: "banner",
  CATEGORY: "category",
  ADD_CATEGORY: "category/add",
  EDIT_CATEGORY_BASE: "category/edit",
  EDIT_CATEGORY: "category/edit/:id",
  PRODUCT: "product",
  ADD_PRODUCT: "product/add",
  EDIT_PRODUCT_BASE: "product/edit",
  EDIT_PRODUCT: "product/edit/:id",
  LOGOUT: "logout",
};
